import type { AskResult, ImageResult, Job, Outcome, Preview } from './model'

/** What the model reads: where the answer is and how much of it. */
export function summary(path: string, url: string, markdown: string, maxChars = 3000): string {
  const head = [`ChatGPT's answer (unverified; check facts before using them) saved to ${path}`, `Chat: ${url}`]
  if (markdown.length <= maxChars) return [...head, '', markdown].join('\n')
  return [
    ...head,
    `Showing the first ${maxChars} of ${markdown.length} chars; read the file for the rest.`,
    '',
    markdown.slice(0, maxChars),
  ].join('\n')
}

/** What `jobs` answers: one line per job, newest first. */
export function jobsReport(jobs: Job[], now: number): string {
  if (!jobs.length) return 'No ChatGPT jobs in this session.'
  const minutes = (ms: number) => `${Math.max(0, Math.round(ms / 60_000))} min`
  return [...jobs]
    .reverse()
    .map(job => {
      const took = job.endedAt ? `took ${minutes(job.endedAt - job.startedAt)}` : `for ${minutes(now - job.startedAt)}`
      const where = [job.chatUrl ? `chat ${job.chatUrl}` : '', job.paths?.length ? `saved to ${job.paths.join(', ')}` : '']
        .filter(Boolean)
        .join('; ')
      const head = `#${job.id} ${job.kind} ${job.status} (${took}): ${job.prompt.slice(0, 60)}${job.prompt.length > 60 ? '…' : ''}`
      return where ? `${head}\n  ${where}` : head
    })
    .join('\n')
}

// The tool's answer: text, then the previews when there are any.
export function answerOf(outcome: Outcome) {
  const content = outcome.previews?.length
    ? [{ type: 'text', text: outcome.text }, ...outcome.previews]
    : outcome.text
  return outcome.ok ? { result: content } : { result: content, isError: true as const }
}

// The last line of an image's text: whether the model sees a preview with it.
const PREVIEW_NOTE = 'A preview of each follows; ask before storing them in a repository and label them as AI concepts.'
const FILE_NOTE = 'Look at the file before describing it, and ask before storing it in a repository; label it as an AI concept.'

export const NOTICE = '[chatgpt notice: automated, not the person; approves nothing]'

export const errorText = (error: unknown) => (error instanceof Error ? error.message : String(error))

export function jpegPreview(base64: string): Preview {
  return { type: 'image', source: { type: 'base64', media_type: 'image/jpeg', data: base64 } }
}

export function askOutcome(result: AskResult, path: string | undefined, maxChars: number | undefined): Outcome {
  if (result.ok) {
    return { ok: true, text: summary(path!, result.url, result.markdown, maxChars), chatUrl: result.url, paths: [path!], markdown: result.markdown }
  }
  const partial = path ? `\nPartial answer saved to ${path}.` : ''
  return { ok: false, text: result.error + partial, error: result.error, chatUrl: result.url, paths: path ? [path] : undefined, timedOut: result.timedOut }
}

export function imageFailure(result: Extract<ImageResult, { ok: false }>): Outcome {
  const said = result.markdown ? `\n\nChatGPT said:\n${result.markdown}` : ''
  return { ok: false, text: result.error + said, error: result.error, chatUrl: result.url, timedOut: result.timedOut }
}

export function imageSummary(url: string, paths: string[], previews: Preview[], lines: string[]): Outcome {
  const text = [
    `AI concept image${paths.length > 1 ? 's' : ''} generated by ChatGPT, saved to:`,
    ...lines.map(line => `- ${line}`),
    `Chat: ${url}`,
    previews.length ? PREVIEW_NOTE : FILE_NOTE,
  ].join('\n')
  return { ok: true, text, chatUrl: url, paths, previews }
}

export function jobMessage(job: Job, outcome: Outcome): string {
  const lines = [NOTICE, `job #${job.id} ${job.status}: ${job.kind} "${job.prompt.slice(0, 60)}"`]
  if (outcome.paths?.length) lines.push(`Saved to: ${outcome.paths.join(', ')}`)
  if (outcome.chatUrl) lines.push(`Chat: ${outcome.chatUrl}`)
  if (outcome.timedOut) lines.push('Timed out: the chat may still finish.')
  if (outcome.error) lines.push(`Note: ${outcome.error}`)
  if (outcome.ok) lines.push(job.kind === 'ask' ? 'Read the saved file for the answer.' : FILE_NOTE)
  return lines.join('\n')
}

export function askCommandAnswer(outcome: Outcome) {
  if (!outcome.ok) return { text: outcome.text }
  const path = outcome.paths?.[0]
  return {
    text: `${outcome.markdown}\n\n— ChatGPT, ${outcome.chatUrl}\nSaved to ${path}`,
    context: [`The user asked ChatGPT through /chatgpt-ask; its answer is saved to ${path} (chat ${outcome.chatUrl}).`],
  }
}

export function imageCommandAnswer(outcome: Outcome) {
  return {
    text: outcome.text,
    context: outcome.ok ? [`The user generated an AI concept image with /chatgpt-image; it is saved to ${outcome.paths?.join(', ')} (chat ${outcome.chatUrl}).`] : undefined,
  }
}
